import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";
import Sidebar from "@/common/components/Sidebar";
import Navbar from "@/common/components/Navbar";
import { ReduxProvider } from '@/redux/providers/ReduxProvider'

// Load Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Adjust as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ReduxProvider>
          <div className="h-screen flex w-full">
            <Sidebar isOpen={true} />
            <main className="relative left-10 w-full overflow-x-hidden overflow-y-scroll">
              <Navbar />
              <div className="relative left-4">{children}</div>
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
